# apogee docker-compose.yml

version: '3'

services:
  mysqldb:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=MysqlRoot
    ports:
      - 3306:3306
    volumes:
      - "./dbdata:/var/lib/mysql"

  phpweb:
    build: './php-apache/'
    volumes:
      - "./apogee-phpci3:/var/www/html/"
    ports:
      - 80:80
    depends_on:
      - mysqldb

